// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/proto/country.proto

package protobuf;

public final class RegionProtos {
  private RegionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Region)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string lang = 2;</code>
     * @return Whether the lang field is set.
     */
    boolean hasLang();
    /**
     * <code>optional string lang = 2;</code>
     * @return The lang.
     */
    java.lang.String getLang();
    /**
     * <code>optional string lang = 2;</code>
     * @return The bytes for lang.
     */
    com.google.protobuf.ByteString
        getLangBytes();

    /**
     * <code>optional string type = 3;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional string type = 3;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 3;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string roads = 4;</code>
     * @return Whether the roads field is set.
     */
    boolean hasRoads();
    /**
     * <code>optional string roads = 4;</code>
     * @return The roads.
     */
    java.lang.String getRoads();
    /**
     * <code>optional string roads = 4;</code>
     * @return The bytes for roads.
     */
    com.google.protobuf.ByteString
        getRoadsBytes();

    /**
     * <code>optional string translate = 5;</code>
     * @return Whether the translate field is set.
     */
    boolean hasTranslate();
    /**
     * <code>optional string translate = 5;</code>
     * @return The translate.
     */
    java.lang.String getTranslate();
    /**
     * <code>optional string translate = 5;</code>
     * @return The bytes for translate.
     */
    com.google.protobuf.ByteString
        getTranslateBytes();

    /**
     * <code>optional string srtm = 6;</code>
     * @return Whether the srtm field is set.
     */
    boolean hasSrtm();
    /**
     * <code>optional string srtm = 6;</code>
     * @return The srtm.
     */
    java.lang.String getSrtm();
    /**
     * <code>optional string srtm = 6;</code>
     * @return The bytes for srtm.
     */
    com.google.protobuf.ByteString
        getSrtmBytes();

    /**
     * <code>optional string hillshade = 7;</code>
     * @return Whether the hillshade field is set.
     */
    boolean hasHillshade();
    /**
     * <code>optional string hillshade = 7;</code>
     * @return The hillshade.
     */
    java.lang.String getHillshade();
    /**
     * <code>optional string hillshade = 7;</code>
     * @return The bytes for hillshade.
     */
    com.google.protobuf.ByteString
        getHillshadeBytes();

    /**
     * <code>optional string wiki = 8;</code>
     * @return Whether the wiki field is set.
     */
    boolean hasWiki();
    /**
     * <code>optional string wiki = 8;</code>
     * @return The wiki.
     */
    java.lang.String getWiki();
    /**
     * <code>optional string wiki = 8;</code>
     * @return The bytes for wiki.
     */
    com.google.protobuf.ByteString
        getWikiBytes();

    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    java.util.List<protobuf.RegionProtos.Region.Point> 
        getPointList();
    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    protobuf.RegionProtos.Region.Point getPoint(int index);
    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    int getPointCount();
    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    java.util.List<? extends protobuf.RegionProtos.Region.PointOrBuilder> 
        getPointOrBuilderList();
    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    protobuf.RegionProtos.Region.PointOrBuilder getPointOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.Region}
   */
  public static final class Region extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Region)
      RegionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Region.newBuilder() to construct.
    private Region(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Region() {
      name_ = "";
      lang_ = "";
      type_ = "";
      roads_ = "";
      translate_ = "";
      srtm_ = "";
      hillshade_ = "";
      wiki_ = "";
      point_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Region();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Region(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              lang_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              type_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              roads_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              translate_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              srtm_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              hillshade_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              wiki_ = bs;
              break;
            }
            case 90: {
              if (!((mutable_bitField0_ & 0x00000100) != 0)) {
                point_ = new java.util.ArrayList<protobuf.RegionProtos.Region.Point>();
                mutable_bitField0_ |= 0x00000100;
              }
              point_.add(
                  input.readMessage(protobuf.RegionProtos.Region.Point.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) != 0)) {
          point_ = java.util.Collections.unmodifiableList(point_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.RegionProtos.internal_static_protobuf_Region_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.RegionProtos.internal_static_protobuf_Region_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.RegionProtos.Region.class, protobuf.RegionProtos.Region.Builder.class);
    }

    public interface PointOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.Region.Point)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required double lat = 9;</code>
       * @return Whether the lat field is set.
       */
      boolean hasLat();
      /**
       * <code>required double lat = 9;</code>
       * @return The lat.
       */
      double getLat();

      /**
       * <code>required double lon = 10;</code>
       * @return Whether the lon field is set.
       */
      boolean hasLon();
      /**
       * <code>required double lon = 10;</code>
       * @return The lon.
       */
      double getLon();
    }
    /**
     * Protobuf type {@code protobuf.Region.Point}
     */
    public static final class Point extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protobuf.Region.Point)
        PointOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Point.newBuilder() to construct.
      private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Point() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Point();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Point(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 73: {
                bitField0_ |= 0x00000001;
                lat_ = input.readDouble();
                break;
              }
              case 81: {
                bitField0_ |= 0x00000002;
                lon_ = input.readDouble();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.RegionProtos.internal_static_protobuf_Region_Point_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.RegionProtos.internal_static_protobuf_Region_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.RegionProtos.Region.Point.class, protobuf.RegionProtos.Region.Point.Builder.class);
      }

      private int bitField0_;
      public static final int LAT_FIELD_NUMBER = 9;
      private double lat_;
      /**
       * <code>required double lat = 9;</code>
       * @return Whether the lat field is set.
       */
      @java.lang.Override
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required double lat = 9;</code>
       * @return The lat.
       */
      @java.lang.Override
      public double getLat() {
        return lat_;
      }

      public static final int LON_FIELD_NUMBER = 10;
      private double lon_;
      /**
       * <code>required double lon = 10;</code>
       * @return Whether the lon field is set.
       */
      @java.lang.Override
      public boolean hasLon() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double lon = 10;</code>
       * @return The lon.
       */
      @java.lang.Override
      public double getLon() {
        return lon_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasLat()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLon()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeDouble(9, lat_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeDouble(10, lon_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(9, lat_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(10, lon_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof protobuf.RegionProtos.Region.Point)) {
          return super.equals(obj);
        }
        protobuf.RegionProtos.Region.Point other = (protobuf.RegionProtos.Region.Point) obj;

        if (hasLat() != other.hasLat()) return false;
        if (hasLat()) {
          if (java.lang.Double.doubleToLongBits(getLat())
              != java.lang.Double.doubleToLongBits(
                  other.getLat())) return false;
        }
        if (hasLon() != other.hasLon()) return false;
        if (hasLon()) {
          if (java.lang.Double.doubleToLongBits(getLon())
              != java.lang.Double.doubleToLongBits(
                  other.getLon())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasLat()) {
          hash = (37 * hash) + LAT_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getLat()));
        }
        if (hasLon()) {
          hash = (37 * hash) + LON_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getLon()));
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static protobuf.RegionProtos.Region.Point parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobuf.RegionProtos.Region.Point parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobuf.RegionProtos.Region.Point parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobuf.RegionProtos.Region.Point parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobuf.RegionProtos.Region.Point parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobuf.RegionProtos.Region.Point parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobuf.RegionProtos.Region.Point parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protobuf.RegionProtos.Region.Point parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static protobuf.RegionProtos.Region.Point parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static protobuf.RegionProtos.Region.Point parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static protobuf.RegionProtos.Region.Point parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protobuf.RegionProtos.Region.Point parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(protobuf.RegionProtos.Region.Point prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobuf.Region.Point}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protobuf.Region.Point)
          protobuf.RegionProtos.Region.PointOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protobuf.RegionProtos.internal_static_protobuf_Region_Point_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protobuf.RegionProtos.internal_static_protobuf_Region_Point_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protobuf.RegionProtos.Region.Point.class, protobuf.RegionProtos.Region.Point.Builder.class);
        }

        // Construct using protobuf.RegionProtos.Region.Point.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          lat_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          lon_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protobuf.RegionProtos.internal_static_protobuf_Region_Point_descriptor;
        }

        @java.lang.Override
        public protobuf.RegionProtos.Region.Point getDefaultInstanceForType() {
          return protobuf.RegionProtos.Region.Point.getDefaultInstance();
        }

        @java.lang.Override
        public protobuf.RegionProtos.Region.Point build() {
          protobuf.RegionProtos.Region.Point result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public protobuf.RegionProtos.Region.Point buildPartial() {
          protobuf.RegionProtos.Region.Point result = new protobuf.RegionProtos.Region.Point(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.lat_ = lat_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.lon_ = lon_;
            to_bitField0_ |= 0x00000002;
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protobuf.RegionProtos.Region.Point) {
            return mergeFrom((protobuf.RegionProtos.Region.Point)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protobuf.RegionProtos.Region.Point other) {
          if (other == protobuf.RegionProtos.Region.Point.getDefaultInstance()) return this;
          if (other.hasLat()) {
            setLat(other.getLat());
          }
          if (other.hasLon()) {
            setLon(other.getLon());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasLat()) {
            return false;
          }
          if (!hasLon()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protobuf.RegionProtos.Region.Point parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protobuf.RegionProtos.Region.Point) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private double lat_ ;
        /**
         * <code>required double lat = 9;</code>
         * @return Whether the lat field is set.
         */
        @java.lang.Override
        public boolean hasLat() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required double lat = 9;</code>
         * @return The lat.
         */
        @java.lang.Override
        public double getLat() {
          return lat_;
        }
        /**
         * <code>required double lat = 9;</code>
         * @param value The lat to set.
         * @return This builder for chaining.
         */
        public Builder setLat(double value) {
          bitField0_ |= 0x00000001;
          lat_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double lat = 9;</code>
         * @return This builder for chaining.
         */
        public Builder clearLat() {
          bitField0_ = (bitField0_ & ~0x00000001);
          lat_ = 0D;
          onChanged();
          return this;
        }

        private double lon_ ;
        /**
         * <code>required double lon = 10;</code>
         * @return Whether the lon field is set.
         */
        @java.lang.Override
        public boolean hasLon() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required double lon = 10;</code>
         * @return The lon.
         */
        @java.lang.Override
        public double getLon() {
          return lon_;
        }
        /**
         * <code>required double lon = 10;</code>
         * @param value The lon to set.
         * @return This builder for chaining.
         */
        public Builder setLon(double value) {
          bitField0_ |= 0x00000002;
          lon_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double lon = 10;</code>
         * @return This builder for chaining.
         */
        public Builder clearLon() {
          bitField0_ = (bitField0_ & ~0x00000002);
          lon_ = 0D;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protobuf.Region.Point)
      }

      // @@protoc_insertion_point(class_scope:protobuf.Region.Point)
      private static final protobuf.RegionProtos.Region.Point DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new protobuf.RegionProtos.Region.Point();
      }

      public static protobuf.RegionProtos.Region.Point getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Point>
          PARSER = new com.google.protobuf.AbstractParser<Point>() {
        @java.lang.Override
        public Point parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Point(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Point> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Point> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public protobuf.RegionProtos.Region.Point getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANG_FIELD_NUMBER = 2;
    private volatile java.lang.Object lang_;
    /**
     * <code>optional string lang = 2;</code>
     * @return Whether the lang field is set.
     */
    @java.lang.Override
    public boolean hasLang() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string lang = 2;</code>
     * @return The lang.
     */
    @java.lang.Override
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lang_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lang = 2;</code>
     * @return The bytes for lang.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object type_;
    /**
     * <code>optional string type = 3;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string type = 3;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROADS_FIELD_NUMBER = 4;
    private volatile java.lang.Object roads_;
    /**
     * <code>optional string roads = 4;</code>
     * @return Whether the roads field is set.
     */
    @java.lang.Override
    public boolean hasRoads() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string roads = 4;</code>
     * @return The roads.
     */
    @java.lang.Override
    public java.lang.String getRoads() {
      java.lang.Object ref = roads_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          roads_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string roads = 4;</code>
     * @return The bytes for roads.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoadsBytes() {
      java.lang.Object ref = roads_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roads_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSLATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object translate_;
    /**
     * <code>optional string translate = 5;</code>
     * @return Whether the translate field is set.
     */
    @java.lang.Override
    public boolean hasTranslate() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string translate = 5;</code>
     * @return The translate.
     */
    @java.lang.Override
    public java.lang.String getTranslate() {
      java.lang.Object ref = translate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          translate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string translate = 5;</code>
     * @return The bytes for translate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTranslateBytes() {
      java.lang.Object ref = translate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        translate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SRTM_FIELD_NUMBER = 6;
    private volatile java.lang.Object srtm_;
    /**
     * <code>optional string srtm = 6;</code>
     * @return Whether the srtm field is set.
     */
    @java.lang.Override
    public boolean hasSrtm() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string srtm = 6;</code>
     * @return The srtm.
     */
    @java.lang.Override
    public java.lang.String getSrtm() {
      java.lang.Object ref = srtm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          srtm_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string srtm = 6;</code>
     * @return The bytes for srtm.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSrtmBytes() {
      java.lang.Object ref = srtm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srtm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HILLSHADE_FIELD_NUMBER = 7;
    private volatile java.lang.Object hillshade_;
    /**
     * <code>optional string hillshade = 7;</code>
     * @return Whether the hillshade field is set.
     */
    @java.lang.Override
    public boolean hasHillshade() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string hillshade = 7;</code>
     * @return The hillshade.
     */
    @java.lang.Override
    public java.lang.String getHillshade() {
      java.lang.Object ref = hillshade_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hillshade_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hillshade = 7;</code>
     * @return The bytes for hillshade.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHillshadeBytes() {
      java.lang.Object ref = hillshade_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hillshade_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WIKI_FIELD_NUMBER = 8;
    private volatile java.lang.Object wiki_;
    /**
     * <code>optional string wiki = 8;</code>
     * @return Whether the wiki field is set.
     */
    @java.lang.Override
    public boolean hasWiki() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string wiki = 8;</code>
     * @return The wiki.
     */
    @java.lang.Override
    public java.lang.String getWiki() {
      java.lang.Object ref = wiki_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wiki_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string wiki = 8;</code>
     * @return The bytes for wiki.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWikiBytes() {
      java.lang.Object ref = wiki_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wiki_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POINT_FIELD_NUMBER = 11;
    private java.util.List<protobuf.RegionProtos.Region.Point> point_;
    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    @java.lang.Override
    public java.util.List<protobuf.RegionProtos.Region.Point> getPointList() {
      return point_;
    }
    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    @java.lang.Override
    public java.util.List<? extends protobuf.RegionProtos.Region.PointOrBuilder> 
        getPointOrBuilderList() {
      return point_;
    }
    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    @java.lang.Override
    public int getPointCount() {
      return point_.size();
    }
    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    @java.lang.Override
    public protobuf.RegionProtos.Region.Point getPoint(int index) {
      return point_.get(index);
    }
    /**
     * <code>repeated .protobuf.Region.Point point = 11;</code>
     */
    @java.lang.Override
    public protobuf.RegionProtos.Region.PointOrBuilder getPointOrBuilder(
        int index) {
      return point_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPointCount(); i++) {
        if (!getPoint(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lang_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, roads_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, translate_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, srtm_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, hillshade_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, wiki_);
      }
      for (int i = 0; i < point_.size(); i++) {
        output.writeMessage(11, point_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lang_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, roads_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, translate_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, srtm_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, hillshade_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, wiki_);
      }
      for (int i = 0; i < point_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, point_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.RegionProtos.Region)) {
        return super.equals(obj);
      }
      protobuf.RegionProtos.Region other = (protobuf.RegionProtos.Region) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasLang() != other.hasLang()) return false;
      if (hasLang()) {
        if (!getLang()
            .equals(other.getLang())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasRoads() != other.hasRoads()) return false;
      if (hasRoads()) {
        if (!getRoads()
            .equals(other.getRoads())) return false;
      }
      if (hasTranslate() != other.hasTranslate()) return false;
      if (hasTranslate()) {
        if (!getTranslate()
            .equals(other.getTranslate())) return false;
      }
      if (hasSrtm() != other.hasSrtm()) return false;
      if (hasSrtm()) {
        if (!getSrtm()
            .equals(other.getSrtm())) return false;
      }
      if (hasHillshade() != other.hasHillshade()) return false;
      if (hasHillshade()) {
        if (!getHillshade()
            .equals(other.getHillshade())) return false;
      }
      if (hasWiki() != other.hasWiki()) return false;
      if (hasWiki()) {
        if (!getWiki()
            .equals(other.getWiki())) return false;
      }
      if (!getPointList()
          .equals(other.getPointList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasLang()) {
        hash = (37 * hash) + LANG_FIELD_NUMBER;
        hash = (53 * hash) + getLang().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasRoads()) {
        hash = (37 * hash) + ROADS_FIELD_NUMBER;
        hash = (53 * hash) + getRoads().hashCode();
      }
      if (hasTranslate()) {
        hash = (37 * hash) + TRANSLATE_FIELD_NUMBER;
        hash = (53 * hash) + getTranslate().hashCode();
      }
      if (hasSrtm()) {
        hash = (37 * hash) + SRTM_FIELD_NUMBER;
        hash = (53 * hash) + getSrtm().hashCode();
      }
      if (hasHillshade()) {
        hash = (37 * hash) + HILLSHADE_FIELD_NUMBER;
        hash = (53 * hash) + getHillshade().hashCode();
      }
      if (hasWiki()) {
        hash = (37 * hash) + WIKI_FIELD_NUMBER;
        hash = (53 * hash) + getWiki().hashCode();
      }
      if (getPointCount() > 0) {
        hash = (37 * hash) + POINT_FIELD_NUMBER;
        hash = (53 * hash) + getPointList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.RegionProtos.Region parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.RegionProtos.Region parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.RegionProtos.Region parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.RegionProtos.Region parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.RegionProtos.Region parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.RegionProtos.Region parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.RegionProtos.Region parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.RegionProtos.Region parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.RegionProtos.Region parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.RegionProtos.Region parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.RegionProtos.Region parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.RegionProtos.Region parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.RegionProtos.Region prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Region}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Region)
        protobuf.RegionProtos.RegionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.RegionProtos.internal_static_protobuf_Region_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.RegionProtos.internal_static_protobuf_Region_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.RegionProtos.Region.class, protobuf.RegionProtos.Region.Builder.class);
      }

      // Construct using protobuf.RegionProtos.Region.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPointFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lang_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        roads_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        translate_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        srtm_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        hillshade_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        wiki_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          pointBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.RegionProtos.internal_static_protobuf_Region_descriptor;
      }

      @java.lang.Override
      public protobuf.RegionProtos.Region getDefaultInstanceForType() {
        return protobuf.RegionProtos.Region.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.RegionProtos.Region build() {
        protobuf.RegionProtos.Region result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.RegionProtos.Region buildPartial() {
        protobuf.RegionProtos.Region result = new protobuf.RegionProtos.Region(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lang_ = lang_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.roads_ = roads_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.translate_ = translate_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.srtm_ = srtm_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.hillshade_ = hillshade_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.wiki_ = wiki_;
        if (pointBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0)) {
            point_ = java.util.Collections.unmodifiableList(point_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.point_ = point_;
        } else {
          result.point_ = pointBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.RegionProtos.Region) {
          return mergeFrom((protobuf.RegionProtos.Region)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.RegionProtos.Region other) {
        if (other == protobuf.RegionProtos.Region.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLang()) {
          bitField0_ |= 0x00000002;
          lang_ = other.lang_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasRoads()) {
          bitField0_ |= 0x00000008;
          roads_ = other.roads_;
          onChanged();
        }
        if (other.hasTranslate()) {
          bitField0_ |= 0x00000010;
          translate_ = other.translate_;
          onChanged();
        }
        if (other.hasSrtm()) {
          bitField0_ |= 0x00000020;
          srtm_ = other.srtm_;
          onChanged();
        }
        if (other.hasHillshade()) {
          bitField0_ |= 0x00000040;
          hillshade_ = other.hillshade_;
          onChanged();
        }
        if (other.hasWiki()) {
          bitField0_ |= 0x00000080;
          wiki_ = other.wiki_;
          onChanged();
        }
        if (pointBuilder_ == null) {
          if (!other.point_.isEmpty()) {
            if (point_.isEmpty()) {
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensurePointIsMutable();
              point_.addAll(other.point_);
            }
            onChanged();
          }
        } else {
          if (!other.point_.isEmpty()) {
            if (pointBuilder_.isEmpty()) {
              pointBuilder_.dispose();
              pointBuilder_ = null;
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000100);
              pointBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPointFieldBuilder() : null;
            } else {
              pointBuilder_.addAllMessages(other.point_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        for (int i = 0; i < getPointCount(); i++) {
          if (!getPoint(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.RegionProtos.Region parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.RegionProtos.Region) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lang_ = "";
      /**
       * <code>optional string lang = 2;</code>
       * @return Whether the lang field is set.
       */
      public boolean hasLang() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string lang = 2;</code>
       * @return The lang.
       */
      public java.lang.String getLang() {
        java.lang.Object ref = lang_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lang_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lang = 2;</code>
       * @return The bytes for lang.
       */
      public com.google.protobuf.ByteString
          getLangBytes() {
        java.lang.Object ref = lang_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lang_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lang = 2;</code>
       * @param value The lang to set.
       * @return This builder for chaining.
       */
      public Builder setLang(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lang_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lang = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLang() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lang_ = getDefaultInstance().getLang();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lang = 2;</code>
       * @param value The bytes for lang to set.
       * @return This builder for chaining.
       */
      public Builder setLangBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lang_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 3;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string type = 3;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 3;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object roads_ = "";
      /**
       * <code>optional string roads = 4;</code>
       * @return Whether the roads field is set.
       */
      public boolean hasRoads() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string roads = 4;</code>
       * @return The roads.
       */
      public java.lang.String getRoads() {
        java.lang.Object ref = roads_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            roads_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string roads = 4;</code>
       * @return The bytes for roads.
       */
      public com.google.protobuf.ByteString
          getRoadsBytes() {
        java.lang.Object ref = roads_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roads_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string roads = 4;</code>
       * @param value The roads to set.
       * @return This builder for chaining.
       */
      public Builder setRoads(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        roads_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string roads = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoads() {
        bitField0_ = (bitField0_ & ~0x00000008);
        roads_ = getDefaultInstance().getRoads();
        onChanged();
        return this;
      }
      /**
       * <code>optional string roads = 4;</code>
       * @param value The bytes for roads to set.
       * @return This builder for chaining.
       */
      public Builder setRoadsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        roads_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object translate_ = "";
      /**
       * <code>optional string translate = 5;</code>
       * @return Whether the translate field is set.
       */
      public boolean hasTranslate() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string translate = 5;</code>
       * @return The translate.
       */
      public java.lang.String getTranslate() {
        java.lang.Object ref = translate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            translate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string translate = 5;</code>
       * @return The bytes for translate.
       */
      public com.google.protobuf.ByteString
          getTranslateBytes() {
        java.lang.Object ref = translate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          translate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string translate = 5;</code>
       * @param value The translate to set.
       * @return This builder for chaining.
       */
      public Builder setTranslate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        translate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string translate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTranslate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        translate_ = getDefaultInstance().getTranslate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string translate = 5;</code>
       * @param value The bytes for translate to set.
       * @return This builder for chaining.
       */
      public Builder setTranslateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        translate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object srtm_ = "";
      /**
       * <code>optional string srtm = 6;</code>
       * @return Whether the srtm field is set.
       */
      public boolean hasSrtm() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string srtm = 6;</code>
       * @return The srtm.
       */
      public java.lang.String getSrtm() {
        java.lang.Object ref = srtm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            srtm_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string srtm = 6;</code>
       * @return The bytes for srtm.
       */
      public com.google.protobuf.ByteString
          getSrtmBytes() {
        java.lang.Object ref = srtm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          srtm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string srtm = 6;</code>
       * @param value The srtm to set.
       * @return This builder for chaining.
       */
      public Builder setSrtm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        srtm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string srtm = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrtm() {
        bitField0_ = (bitField0_ & ~0x00000020);
        srtm_ = getDefaultInstance().getSrtm();
        onChanged();
        return this;
      }
      /**
       * <code>optional string srtm = 6;</code>
       * @param value The bytes for srtm to set.
       * @return This builder for chaining.
       */
      public Builder setSrtmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        srtm_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hillshade_ = "";
      /**
       * <code>optional string hillshade = 7;</code>
       * @return Whether the hillshade field is set.
       */
      public boolean hasHillshade() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string hillshade = 7;</code>
       * @return The hillshade.
       */
      public java.lang.String getHillshade() {
        java.lang.Object ref = hillshade_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hillshade_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hillshade = 7;</code>
       * @return The bytes for hillshade.
       */
      public com.google.protobuf.ByteString
          getHillshadeBytes() {
        java.lang.Object ref = hillshade_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hillshade_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hillshade = 7;</code>
       * @param value The hillshade to set.
       * @return This builder for chaining.
       */
      public Builder setHillshade(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        hillshade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hillshade = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearHillshade() {
        bitField0_ = (bitField0_ & ~0x00000040);
        hillshade_ = getDefaultInstance().getHillshade();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hillshade = 7;</code>
       * @param value The bytes for hillshade to set.
       * @return This builder for chaining.
       */
      public Builder setHillshadeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        hillshade_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object wiki_ = "";
      /**
       * <code>optional string wiki = 8;</code>
       * @return Whether the wiki field is set.
       */
      public boolean hasWiki() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional string wiki = 8;</code>
       * @return The wiki.
       */
      public java.lang.String getWiki() {
        java.lang.Object ref = wiki_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            wiki_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string wiki = 8;</code>
       * @return The bytes for wiki.
       */
      public com.google.protobuf.ByteString
          getWikiBytes() {
        java.lang.Object ref = wiki_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wiki_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string wiki = 8;</code>
       * @param value The wiki to set.
       * @return This builder for chaining.
       */
      public Builder setWiki(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        wiki_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string wiki = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearWiki() {
        bitField0_ = (bitField0_ & ~0x00000080);
        wiki_ = getDefaultInstance().getWiki();
        onChanged();
        return this;
      }
      /**
       * <code>optional string wiki = 8;</code>
       * @param value The bytes for wiki to set.
       * @return This builder for chaining.
       */
      public Builder setWikiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        wiki_ = value;
        onChanged();
        return this;
      }

      private java.util.List<protobuf.RegionProtos.Region.Point> point_ =
        java.util.Collections.emptyList();
      private void ensurePointIsMutable() {
        if (!((bitField0_ & 0x00000100) != 0)) {
          point_ = new java.util.ArrayList<protobuf.RegionProtos.Region.Point>(point_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.RegionProtos.Region.Point, protobuf.RegionProtos.Region.Point.Builder, protobuf.RegionProtos.Region.PointOrBuilder> pointBuilder_;

      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public java.util.List<protobuf.RegionProtos.Region.Point> getPointList() {
        if (pointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(point_);
        } else {
          return pointBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public int getPointCount() {
        if (pointBuilder_ == null) {
          return point_.size();
        } else {
          return pointBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public protobuf.RegionProtos.Region.Point getPoint(int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);
        } else {
          return pointBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public Builder setPoint(
          int index, protobuf.RegionProtos.Region.Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.set(index, value);
          onChanged();
        } else {
          pointBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public Builder setPoint(
          int index, protobuf.RegionProtos.Region.Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public Builder addPoint(protobuf.RegionProtos.Region.Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(value);
          onChanged();
        } else {
          pointBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public Builder addPoint(
          int index, protobuf.RegionProtos.Region.Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(index, value);
          onChanged();
        } else {
          pointBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public Builder addPoint(
          protobuf.RegionProtos.Region.Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public Builder addPoint(
          int index, protobuf.RegionProtos.Region.Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public Builder addAllPoint(
          java.lang.Iterable<? extends protobuf.RegionProtos.Region.Point> values) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, point_);
          onChanged();
        } else {
          pointBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public Builder clearPoint() {
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          pointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public Builder removePoint(int index) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.remove(index);
          onChanged();
        } else {
          pointBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public protobuf.RegionProtos.Region.Point.Builder getPointBuilder(
          int index) {
        return getPointFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public protobuf.RegionProtos.Region.PointOrBuilder getPointOrBuilder(
          int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);  } else {
          return pointBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public java.util.List<? extends protobuf.RegionProtos.Region.PointOrBuilder> 
           getPointOrBuilderList() {
        if (pointBuilder_ != null) {
          return pointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(point_);
        }
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public protobuf.RegionProtos.Region.Point.Builder addPointBuilder() {
        return getPointFieldBuilder().addBuilder(
            protobuf.RegionProtos.Region.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public protobuf.RegionProtos.Region.Point.Builder addPointBuilder(
          int index) {
        return getPointFieldBuilder().addBuilder(
            index, protobuf.RegionProtos.Region.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Region.Point point = 11;</code>
       */
      public java.util.List<protobuf.RegionProtos.Region.Point.Builder> 
           getPointBuilderList() {
        return getPointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.RegionProtos.Region.Point, protobuf.RegionProtos.Region.Point.Builder, protobuf.RegionProtos.Region.PointOrBuilder> 
          getPointFieldBuilder() {
        if (pointBuilder_ == null) {
          pointBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protobuf.RegionProtos.Region.Point, protobuf.RegionProtos.Region.Point.Builder, protobuf.RegionProtos.Region.PointOrBuilder>(
                  point_,
                  ((bitField0_ & 0x00000100) != 0),
                  getParentForChildren(),
                  isClean());
          point_ = null;
        }
        return pointBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Region)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Region)
    private static final protobuf.RegionProtos.Region DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.RegionProtos.Region();
    }

    public static protobuf.RegionProtos.Region getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Region>
        PARSER = new com.google.protobuf.AbstractParser<Region>() {
      @java.lang.Override
      public Region parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Region(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Region> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Region> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.RegionProtos.Region getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Region_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Region_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Region_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Region_Point_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"main/resources/proto/country.proto\022\010pr" +
      "otobuf\"\315\001\n\006Region\022\014\n\004name\030\001 \002(\t\022\014\n\004lang\030" +
      "\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\r\n\005roads\030\004 \001(\t\022\021\n\ttr" +
      "anslate\030\005 \001(\t\022\014\n\004srtm\030\006 \001(\t\022\021\n\thillshade" +
      "\030\007 \001(\t\022\014\n\004wiki\030\010 \001(\t\022%\n\005point\030\013 \003(\0132\026.pr" +
      "otobuf.Region.Point\032!\n\005Point\022\013\n\003lat\030\t \002(" +
      "\001\022\013\n\003lon\030\n \002(\001B\030\n\010protobufB\014RegionProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_Region_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Region_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Region_descriptor,
        new java.lang.String[] { "Name", "Lang", "Type", "Roads", "Translate", "Srtm", "Hillshade", "Wiki", "Point", });
    internal_static_protobuf_Region_Point_descriptor =
      internal_static_protobuf_Region_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_Region_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Region_Point_descriptor,
        new java.lang.String[] { "Lat", "Lon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
